### ISSUE TITLE
Name coincidence

### ISSUE THREAD

**Issue by manixabrat** [rstoenescu/quasar-framework#1]
Hello, I have been developing a personal framework for about 5 years now and I am considering to share it and make it public, however it has come to my attention that, unfortunately, your framework shares the same name as mine. I am writing this issue in order to find out if it would be a problem for you and supposedly to find a solution to the problem. Thank you for your attention and if no response is given I will assume that everything is alright.

**Comment by rstoenescu** [comment]
Hi there. I'm not sure what to do. I've already paid for a few services registered under this name and also bought a domain... I'm working on this for a long time as well... I'm also on a tight schedule as I quit my job to make this framework happen so I'm on my own money now, which run out quickly... What do you suggest we do?

**Comment by manixabrat** [comment]
Considering I came up with the name a very long time ago and pretty much most of the stuff is named this way it would be a pain to refactor the entire code. I suppose it wouldn't be a problem for me to share the name as mine would probably not get any popular as it is very specific and most people wouldn't like that, but I thought it would be a good idea to check what you think.

**Comment by rstoenescu** [comment]
Funny thing that I consumed a lot of time deciding on the name :)

I guess it's a lesson to publish early in order to "register" the name for the public. Did you mean to release your project as open-source from the beginning or have decided recently?

I think it will be detrimental and confusing for both projects to have the same name... Maybe you could add a prefix or suffix? Mine is "Quasar Framework"... yours could be "Something Quasar" or "Quasar Something"... Don't let it be just "Quasar". For that you don't have to change any line of code. What do you say?

**Comment by rstoenescu** [comment]
Closing bug. Please reopen if you feel like it.
