### ISSUE TITLE
Implement Flexbox on the List Component

### ISSUE THREAD

**Issue by dobromir-hristov** [rstoenescu/quasar-framework#104]
Would it be a good idea to implement flexbox on the List items to help the item-primary, item-secondary and so on classes? For example I think we could omit the `has-secondary` this way. Also vertical align middle would be possible on the elements. It would just simplify the List and remove some of the helper classes.

**Comment by rstoenescu** [comment]
Initial lists were implemented with Flexbox. The redo in v0.7 does not uses flexbox and fixes some of the initial lists issues. Plus they look much much good. Indeed 'has-secondary' feels like redundant, but this is because of CSS limitations. CSS4 selectors will introduce the previous sibling amongst other great enhancements :) Anyway, getting back to our discussion, re-redoing lists to use flexbox will get us into previous lists troubles. It's a LOT of work too, and not worth it for just being able to remove the `has-secondary` CSS class. Will keep this in mind, but closing for the moment.

**Comment by dobromir-hristov** [comment]
I didn't know it was intended. Pardon me.

**Comment by rstoenescu** [comment]
Hey, don't worry. Log any idea you have. This is the only way we can truly improve things around here ;)
