### ISSUE TITLE
Range enhancements

### ISSUE THREAD

**Issue by CookieJon** [rstoenescu/quasar-framework#123]
Unless I'm blind and it's already there, I'd like to suggest some enhancements to the slider & double slider.  

1. Provide options to display the selected value(s) _all the time_...
1.a When the slider's not being dragged, display value inside the slider itself.
1.b Display value(s) (optionally editable) at each end of a double slider, and before or after a single slider.

2. Provide the ability to drag the whole range (i.e. change upper & lower values at the same time while maintaining the same difference)

I'm happy have a bash at contributing these changes if they're worthwhile, but this would be my first time on github so please be gentle while I'm trudging slowly up the the learning curve. :-)

**Comment by rstoenescu** [comment]
Great thoughts here. Green light on all.

* Both enhancements should be delivered through two new props.
* Point number 2 is especially hard to implement due to clicking/tapping inside of the interval making one of the two ends move to that point.

Give it a try if you like. Welcoming any help! Thanks for opening this!

**Comment by rstoenescu** [comment]
Implemented point 1 through "label-always" prop. Will open a new issue for point 2.

**Comment by rstoenescu** [comment]
Continuing to track the remainder of work to do through #142 Range - drag whole range
