### ISSUE TITLE
Drawer "sliding area" is not large enough

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-framework#28]
The sliding area in which user can slide for opening the drawer is not large enough. In fact, with the Chrome mobile view (devtools), we have to reach the limit of the screen to make the drawer appear, with a very little marge of 1/5 px. For example, with the cursor placed here (see screenshot below), the sliding is not possible. Not tested with other devices, but I think there are issues too.

![image](https://cloud.githubusercontent.com/assets/2403897/17888570/df0188a6-692b-11e6-9433-0000444407f2.png)

**Comment by rstoenescu** [comment]
The width of the element that can open a Drawer (by swipe/pan touch action) is 15px, which means you can't tap on a button or anything on those 15px from left side (or right side, depending where you place your Drawer). Making that area thicker is a bad idea because it means not being able to interact with any element placed beneath it so a larger area with which you can't interact on your UI.

On a real mobile device there's no problem getting the Drawer opened, so I see no problem here. What do you think?

**Comment by mlenormand** [comment]
Well, you're right, the sliding area is 15px width, and not 1 or 5 px. The drawer wait for a few time before being pushed to the right when user starts sliding so I was confused during my tests. So the sliding shown in the above screenshot was OK.
No bug, you can close the issue !

**Comment by rstoenescu** [comment]
Ok, glad I could help.
