### ISSUE TITLE
Parallax speed property

### ISSUE THREAD

**Issue by musicformellons** [rstoenescu/quasar-framework#49]
I thought to have the 'parallax effect' the background should move (at a lower rate) as well.

E.g. see:
http://materializecss.com/parallax-demo.html

**Comment by rstoenescu** [comment]
Are you saying it doesn't move at all? Or that you want to move at a lower rate?

**Comment by musicformellons** [comment]
Tried on chrome and firefox: the text moves but background picture do not move at all. Tried on my android phone: background picture trembles, does not really move.

**Comment by rstoenescu** [comment]
1. What size is the picture you are using?
2. What is the height of the window?
3. Did you set any height to the Parallax (through prop) and which is it?
3. Are you using a layout or not?
4. Is your parallax wrapped in an overflowed element on your page?

**Comment by musicformellons** [comment]
1. I am using your demo component.
2. Does not matter, happens at all sizes.
3, 4, 5, 6  See 1.
7. Chrome and Firefox and Chrome Android mobile. All recent versions.

My screencast is having some quirks otherwise I 'd send you a mp4 of it.

**Comment by rstoenescu** [comment]
Are copy pasting into your app? Does the demo from website works for you?

**Comment by musicformellons** [comment]
I am not using an app. I am just looking at 
http://quasar-framework.org/components/parallax.html

**Comment by rstoenescu** [comment]
Using exactly same environment as you. Latest Chrome, viewing the doc website example. It works. Open up dev tools and refresh the page. Any errors in the console there?

**Comment by rstoenescu** [comment]
Some screenshots to eliminate any confusion. This is how it is indended to be seen while scrolling.


![screenshot from 2016-08-26 19 17 22](https://cloud.githubusercontent.com/assets/4665641/18012423/06e24944-6bc2-11e6-839c-f33578a611ab.png)

![screenshot from 2016-08-26 19 17 24](https://cloud.githubusercontent.com/assets/4665641/18012425/06e5c47a-6bc2-11e6-8bcd-7bb7d7ddbfd6.png)


![screenshot from 2016-08-26 19 17 26](https://cloud.githubusercontent.com/assets/4665641/18012422/06e178de-6bc2-11e6-8500-59556f70a825.png)

![screenshot from 2016-08-26 19 17 30](https://cloud.githubusercontent.com/assets/4665641/18012424/06e4db00-6bc2-11e6-9b24-8b5275a96c1c.png)

**Comment by musicformellons** [comment]
Your screenshots show the behaviour I would expect, but it is not what I get... No errors in the Chrome devtools console... 
The background pictures do shiver/ tremble a little bit... they seem 'stuck'. Weird. As said before it is also on my mobile phone...

**Comment by rstoenescu** [comment]
Weird. I need to reproduce in order to fix it. But can't understand how it would act different on the same browser... Can you investigate a little please on your machine? Fork this repo and try to make something of it. NPM install then "npm run dev".

You'll see some buttons there, click on Parallax. Source of the page is in `/dev/views/parallax.vue`, source for Parallax is in `src/web-components/parallax/parallax.vue`.

Will investigate too, but it's hard if I can't reproduce :(

**Comment by rstoenescu** [comment]
If anyone else is experiencing this please join the discussion.

**Comment by musicformellons** [comment]
When installing as app I have same issue.
![image](https://cloud.githubusercontent.com/assets/10334123/18016775/6d21fc48-6bce-11e6-99fb-26165801bf49.png)


![image](https://cloud.githubusercontent.com/assets/10334123/18016740/40568a44-6bce-11e6-9648-e02a49837700.png)

**Comment by musicformellons** [comment]
Also tried on an ipad. Same problem.

**Comment by musicformellons** [comment]
Just to be 100% sure as when I look more closely at your screencaptures it is also not very clear whether the background picture moves y/n; Expected behaviour would be a moving background picture at different pace then foreground text, like in this example:
http://materializecss.com/parallax-demo.html

**Comment by rstoenescu** [comment]
Omg, lol. But this is intended due to inner workings for scaling any image you give Parallax to work with. The intended effect is just as if you have a window (real life window) through your page and the window moves up or down, showing you different parts of the landscape behind it. From your description I though the background image does not move AT ALL (which would be a bug) as if you keep looking at the same part of the image regardless of the scroll position... aka as if you replace Parallax with a static image :)
What you want is actually an enhancement, to be able to specify some speed for Parallax scroll.

**Comment by musicformellons** [comment]
My goodness, glad we got that sorted out!! I will separately write an issue regarding current feature as it shivers.

**Comment by rstoenescu** [comment]
By default, it will also "move" the image now.
