### ISSUE TITLE
Creating Parameterized Route for Page

### ISSUE THREAD

**Issue by kamilersz** [rstoenescu/quasar-framework#7]
How can I create / configure parameterized route for page, such as #/book/:bookId

I can't seem to find it on the docs. Seems currently the API docs only cover adding custom router.

**Comment by rstoenescu** [comment]
This is currently disabled but will be added back in a future release (v0.2 or v0.3) soon. I need to carefully think this through.

The initial implementation took into consideration a `hash` (Array) property in the Page's manifest file (config.*page-name*.yml). It was working perfectly until I added a feature so that switching between Pages using same Layout does not destroy them (so they can maintain their state). Now I need to re-think how the system will work so the two features be compatible with one another.

**Comment by Atinux** [comment]
It's a good one 👍🏻

**Comment by rstoenescu** [comment]
Will make this a priority.

**Comment by rstoenescu** [comment]
Commit pushed to repository. Will make a new Quasar release and update the documentation website soon.

**Comment by rstoenescu** [comment]
Released Quasar Framework v0.2.0 with lots of new features. It also includes support for parameterized Page routes.

**Comment by Atinux** [comment]
Awesome 👏👏👏
