### ISSUE TITLE
Get the current layout/view component

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-framework#70]
How can we get the current/active layout component instance and the current/active "view" component instance ?
With vue-router, we can get the root Vue instance managed by the router by calling rooter.app (http://router.vuejs.org/en/api/properties.html) but we can't get the active component and subcomponents that are currently injected into the <router-view> tags.

Tried to reference each router-view component with a v-ref tag but doesn't work very well ($refs not available at the beginning of the component lifecycle, and when we pass a "ref" to a child component by a prop value, the prop is not updated when the route changed). Moreover, it's not very clean and the refs have to be passed to all the components hierarchy.
My current use case is to show page-related information in the layout footer/header (for example title, icon, etc.).

I think we can make Quasar better about layout/views management : components are awesome and IMHO, the concept of "universal" app that adapt for all screens/devices fills a real need, but real-world apps with many layouts and views are currently quite difficult to implement. I can open a new issue about my feeling/feedback concerning those aspects.

**Comment by smolinari** [comment]
> I think we can make Quasar better about layout/views management

:+1:  for this, if it isn't already possible.

Scott

**Comment by rstoenescu** [comment]
The last section in this comment is the "must read one". Will close this bug with explanations below. Feel free to reopen if clarifications are needed.

Layout/view components are just Vue components. The Layout component just offers a root/top place from where you build your UI so you can encapsulate tabs, drawers, etc. Current architecture for Quasar is the default way to go for Vue development, which is using a Vue Router to handle page creation. This architecture enables you to structure multiple components to handle different parts of your UI. For example you can have layouts with page that has sub-pages that has sub-pages... It's a kind of "inception" if you know what I mean.

My intuition says you want $refs to your layout or pages because you want to change component data. **The important thing to note here is how to handle communication between components**, specifically components made by you, like your component which describes a layout or a page: Use a store or Vuex. It's not recommended to use $refs because it will soon get very messy and really hard to debug! 
For making a store you got an example in Quasar Play app (which has a store used by "Showcase" layout and its pages). Please read this: http://quasar-framework.org/guide/components-sharing-state.html
